"""empty message

Revision ID: 17097d6e379d
Revises: 6d1c58179beb
Create Date: 2022-05-21 19:27:19.548517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17097d6e379d'
down_revision = '6d1c58179beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'клиент'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'клиент'::character varying"))
    # ### end Alembic commands ###
