"""empty message

Revision ID: 52783a6ae552
Revises: 8c3e6efa6d37
Create Date: 2022-05-22 09:55:19.883665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52783a6ae552'
down_revision = '8c3e6efa6d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post', sa.Column('salary', sa.Numeric(precision=7, scale=2), nullable=False))
    op.add_column('user_post', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_post', 'date')
    op.drop_column('user_post', 'salary')
    # ### end Alembic commands ###
